language: node_js
os: linux
node_js: [
    # check Latest
    14,
    # check current & LTS
    13,
    12,
    # check against oldest supported
    10,
  ]
script: | # this has to be used, otherwise it executes the tests twice (because of "default build script")
  npm run test:coverage
  if [ $? -ne 0 ]; then exit 1; fi # this is added because sometimes it fails and exists with 0 in travis
  if [ $TRAVIS_NODE_VERSION == "12" ]; then echo "Running Coverage" && npm run coverage; fi
stages:
  - compile
  - test
  - deploy
jobs:
  include:
    - name: 'Test Compile Ability'
      stage: compile
      node_js: 10 # use version 10, because that speeds up the task, because travis's default is v10
      script: |
        (npm audit || exit 0)
        npm run build:all # build tests too to check if errors from tsc are present
